system: Update kernel/wifi
Changes:
mmc: Make sure host is disabled on suspend
USB: gadget: f_audio_source: Fix compilation error
USB: gadget: f_audio_source: Fix use after free in audio_unbind
netfilter: xt_IDLETIMER: Rename INTERFACE to LABEL in netlink notification.
net: wireless: bcmdhd: Use correct time from boot for TSF
time: Introduce get_monotonic_boottime and ktime_get_boottime
kstrto*: converting strings to integers done (hopefully) right
-defconfig: jb: regen
video: tegra: add TEGRA_HDMI_74MHZ_LIMIT to config for ICS
Revert "video: tegra3: dc: remove hard coded HDMI rates"
Revert "video: tegra: dc: add tracing information"
Revert "video: tegra: host: Fix error case memory leaks"
-cpufreq: interactive: return back to stock values
video: tegra-ics: dc: allow 6 underflows before reset
-defconfig: jb: reduce TEGRA_EMC_TO_DDR_CLOCK to 2
Revert "video: tegra: dc: remove bandwidth efficiency"
video: tegra: host: Do not panic on hardware timeout
video: tegra: host: Fix error case memory leaks
-video: tegra-ics: remove *3dctx*
block: introduce the BFQ-v4 I/O sched for 2.6.38
-defconfig: jb: set NVMAP_PAGE_POOLS, CPA and unset NVMAP_VPR
USB: gadget: f_audio_source: Fix error handling and increase packet size
cpufreq: interactive: take idle notifications only when active
-defconfig: jb: unset CPA
Revert "ARM: tegra: Enable CPA."
net: wireless: bcmdhd: Fill station_info packet fields
Revert "wireless: bcmdhd: remove __wl_band_5ghz_a.n/2ghz.n_channel in bandlist conditional
-defconfig: jb: enable TRACER
ARM: 6320/1: ftrace: enable dynamic ftrace
-arm: kernel: build: allow -pg only if FUNCTION_TRACER
ARM: 6952/1: fix lockdep warning of "unannotated irqs-off"
ARM: 6319/1: ftrace: add Thumb-2 support to dynamic ftrace
ARM: ftrace: use gas macros to avoid code duplication
-build: exclude -fomit-frame-pointer if FUNCTION_TRACER
ARM: 6318/1: ftrace: fix and update dynamic ftrace
ARM: 6316/1: ftrace: add Thumb-2 support
ARM: 6315/1: ftrace: add ENDPROC annotations
ARM: 6314/1: ftrace: allow build without frame pointers on ARM
-defconfig: jb: add some networking options found in CM's d2 kernel
-defconfig: jb: set DHD_ENABLE_P2P
-defconfig: rename -ics to -jb

Reference:
 https://github.com/cyanogenmod (kernel d2), nv-tegra.nvidia.com (rel-15r7)
 android.googlesource.com, aosp.schiznik.net, github.com/ezterry
 github.com/arco

-Note:
 When HDMI is connected with the adapter, this is thrown:
 WARNING: at kernel/irq/manage.c:290 enable_irq+0x4c/0x74()
 Unbalanced enable for IRQ 106
  -To be investigated.

Change-Id: I2936bc6d3963ab99435615299a7c185475e5ce4e